$ANSIBLE_VAULT;1.1;AES256
31366134373864346264376361623233373032346130643030636332383063353037616533393935
3736623462333665333363373865333063613732393130640a393064653833656565306430643735
36666539653834303933343166343735313863306233623332616239376636666531313933353437
3862333331333136360a306664643363386361633463366631616461366234383035366536656236
65383432303263653735653933316338656430383039383234363465383662366365386234366564
33376130363862613164373139653230373835623331326234343039323839353139633730323064
656563343737303462626431663434373837
